from fastapi import FastAPI, HTTPException
import yt_dlp
import os
import tempfile

app = FastAPI(title="API Musik Vercel dengan Hardcoded Cookies", version="1.0")

# Data cookies Netscape yang langsung ditanam di dalam kode
RAW_COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802860516	__Secure-3PSID	g.a000Bwk3ZfGVSQDS8PUDfe0g-d-52AXBHOTIlkyaMzZTIzERmNpZ4jWqj8CiDKaPdMxSSAPInQACgYKAfESARYSFQHGX2Mi1B9Oj6myrk3eu_cMSbaTjBoVAUF8yKoM01naCJO5adgRfJzDna_r0076
.youtube.com	TRUE	/	FALSE	1803284400	SIDCC	AKEyXzW2TS2Zvum_ppdBvg1m7azbNwmUicUqFC8WfEEbX05o51GTHO32uZRWWxx9SaxfWkw8OBM
.youtube.com	TRUE	/	FALSE	1802860516	SID	g.a000Bwk3ZfGVSQDS8PUDfe0g-d-52AXBHOTIlkyaMzZTIzERmNpZljEwLwyFakjrflfEd2wIhgACgYKAS0SARYSFQHGX2Mifiqcdgfn30QVbyYSrdT8fxoVAUF8yKouDpNVhId65dsj3_wcJQ1X0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803281314	__Secure-1PSIDTS	sidts-CjQBXMw41ZULWYs0O13x9jxAxZdWpDM9IvnB-fdmFDExmmmyDi5WtKGgZ-CryFHudidbwfGgEAA
.youtube.com	TRUE	/	TRUE	1802860516	SAPISID	ARV3wGh_J_VYcf5f/A_VHUJnV2LvHVxtdO
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803284400	__Secure-1PSIDCC	AKEyXzX6M_1xNq04fvuyKZEXQi8dMPbJFisyzDpctevqfhGUJRbxULOzkLGI6aPiA8uG6igIBG4
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802860516	SSID	A1pamT4RDtBQ9pzYG
.youtube.com	TRUE	/	TRUE	1787818886	wide	1
.youtube.com	TRUE	/	TRUE	1802860516	__Secure-1PAPISID	ARV3wGh_J_VYcf5f/A_VHUJnV2LvHVxtdO
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802860516	__Secure-1PSID	g.a000Bwk3ZfGVSQDS8PUDfe0g-d-52AXBHOTIlkyaMzZTIzERmNpZ8Wl4eFpe8_0gWZJSbWGoJQACgYKAdwSARYSFQHGX2Mino97Cu7F21G4gfZWxxomcBoVAUF8yKooH-P5V2gaHxjqvKNwDl830076
.youtube.com	TRUE	/	TRUE	1802860516	__Secure-3PAPISID	ARV3wGh_J_VYcf5f/A_VHUJnV2LvHVxtdO
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803284400	__Secure-3PSIDCC	AKEyXzWmQRAsgXDTv4TmkM1eic4hiMJRv8E7fAxDxHor-NFhMg02h-rh1KuuiyrN9Zc5Gx3u47Q
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803281314	__Secure-3PSIDTS	sidts-CjQBXMw41ZULWYs0O13x9jxAxZdWpDM9IvnB-fdmFDExmmmyDi5WtKGgZ-CryFHudidbwfGgEAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1791180160	__Secure-BUCKET	CJoF
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803195241	__Secure-YENID	17.YTE=Rt6YtysRe9TinKF6ZMSaAnSMzssl36XNe1mO7zVJMAah1L1oUo7bJAQ3AzbsuhQRCT0qPVgWE5OFbDBVM7p1QUnH7Puh-FYL53NQCbQAh6YkezEKEP1N7Rk13vOSSQpqhflmR30LmUvbK0CeDxNoyhemzzZfg3SU2qjToRDouWULoL-IyiDihoBl5Mw9M5tvl5nGjuWwOtlIddn9EufBpzooG7hV3q-44dDXMRaKqrqerHe6kKPhmhVGfersTxHU71wBGhJy2QMCSbf_Telx0MSSYglWUE9GMJLdStuyYAwJsx3_F_uSCIu-UC9R1mw3hUkf2ZKbAFmWStnegIBwqA
.youtube.com	TRUE	/	FALSE	1802860516	APISID	0SdmL4cd2HlMj7FW/ArBblnzlVzrlDRjak
#HttpOnly_.youtube.com	TRUE	/	FALSE	1802860516	HSID	A8XsBUPN9t7EoFUyp
#HttpOnly_.youtube.com	TRUE	/	TRUE	1793700092	LOGIN_INFO	AFmmF2swRQIgay-bAyhjO92UiwG38Pr39fv2FXCoMepfEVzoMcVWTeACIQDvyz0f72N1P592FgwE3igYNuT6bjPa8t0uo7ts-S0XOA:QUQ3MjNmeDhaWVI0VWM5MHRiR3hZNGNoRlhFLTkxbjhtTlZRd1BaNlVpMEd1UmZWNGdzMHNWWHJENzBhblVCa054RmVlbEhqT3ZnX3hkaTFkblhQVm8zQkx4ek1zMDJaa29aME9BZk1IWHpQbGU3cGdRUkdlVlJTUmtLeXZ1WElucVJqcmVHT3R2OWZsZkZzV01UemhzVzc4c3IzdXhFbVFR
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803278450	NID	534=ht3FMW4rRTEC42y0tlbxm-PEKao1NWwKywuajh4VMnCreUvFozrZfajNfouQ6g19LBvXXoTc4LAECKU12HJEqEX46LB1yQPYiqtKFPN2AsuLMuo4HzpaZhBEk_OF9S61JGlvHJaOSjEaIE8jHEFDukxpaeyliFc3pZE6vOETc4oj5a6NUz2KT2S_1lH_WqrMAYoJYp9FJr97e8-mw789LN1ZDE8Du4A3
.youtube.com	TRUE	/	TRUE	1803284392	PREF	repeat=NONE&volume=55&f6=40000000&tz=Asia.Jakarta&f5=30000&autoplay=true&f7=100&gl=ID"""

@app.get("/")
def home():
    return {
        "status": "API Musik dengan Hardcoded Cookies Aktif di Vercel!",
        "endpoint": "/search?q=nama_artis&limit=5"
    }

@app.get("/search")
def search_music(q: str, limit: int = 5):
    if not q:
        raise HTTPException(status_code=400, detail="Parameter query 'q' wajib diisi!")
        
    target_query = f"ytsearch{limit}:{q}"
    
    # Buat file cookies sementara dari variabel RAW_COOKIES di atas
    cookie_file_path = None
    try:
        fd, cookie_file_path = tempfile.mkstemp()
        with os.fdopen(fd, 'w', encoding='utf-8') as tmp:
            tmp.write(RAW_COOKIES)
    except Exception:
        pass

    ydl_opts = {
        'extract_flat': False,
        'skip_download': True,
        'format': '140/bestaudio[protocol^=http]/bestaudio',
    }
    
    if cookie_file_path and os.path.exists(cookie_file_path):
        ydl_opts['cookiefile'] = cookie_file_path

    detailed_song_list = []
    
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            search_results = ydl.extract_info(target_query, download=False)
            entries = search_results.get('entries', [])
            
            for entry in entries:
                title = entry.get('title', 'Unknown Title')
                artist = entry.get('uploader', entry.get('channel', 'Unknown Artist'))
                duration = entry.get('duration_string', 'N/A')
                video_id = entry.get('id', '')
                
                stream_url = f"https://www.youtube.com/watch?v={video_id}" if video_id else entry.get('url', '')
                
                thumbnails = entry.get('thumbnails', [])
                cover_url = thumbnails[-1].get('url', '') if thumbnails else entry.get('thumbnail', '')
                
                direct_audio_url = ""
                formats = entry.get('formats', [])
                
                for f in formats:
                    if f.get('acodec') != 'none' and f.get('vcodec') == 'none':
                        protocol = f.get('protocol', '')
                        url = f.get('url', '')
                        if 'http' in protocol and 'googlevideo.com' in url and 'm3u8' not in url:
                            direct_audio_url = url
                            break
                
                if not direct_audio_url and formats:
                    for f in formats:
                        url = f.get('url', '')
                        if url and 'googlevideo.com' in url and 'm3u8' not in url:
                            direct_audio_url = url
                            break

                song_info = {
                    "judul": title,
                    "artis": artist,
                    "durasi": duration,
                    "video_id": video_id,
                    "link_streaming": stream_url,
                    "link_cover": cover_url,
                    "direct_audio_link": direct_audio_url if direct_audio_url else stream_url
                }
                
                detailed_song_list.append(song_info)
                
        # Bersihkan file temporary cookies
        if cookie_file_path and os.path.exists(cookie_file_path):
            os.remove(cookie_file_path)

        return {
            "query": q,
            "total_ditemukan": len(detailed_song_list),
            "result": detailed_song_list
        }
        
    except Exception as e:
        if cookie_file_path and os.path.exists(cookie_file_path):
            os.remove(cookie_file_path)
        raise HTTPException(status_code=500, detail=str(e))
